project:
  type: website

website:
  title: "All Your Bayes"
  site-url: https://www.allyourbayes.com/
  description: "thoughts on risk and uncertainty in decision support"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme: simplex
    css: styles.css



